### ISSUE TITLE
How to test pretrained model by interpolating 2 input png images?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [feinanshan/M2M_VFI#10]
Thanks for sharing this work!

I'm not seeing where the python script is to interpolate our own images or video.  Typically these code examples have something like this.  Am I just not seeing how to do this, or are there no plans to allow us to evaluate the code in this way?

**Comment by feinanshan** [comment]
The codes can be easily adopted to privately-owned data (that does’t violate the license).  

If having difficulties, post something here so that we can help.

**Comment by feinanshan** [comment]
Hi, I am closing this issue. Feel free to reopen it anytime.

**Comment by noobtoob4lyfe** [comment]
Thanks for the response.  Will do!
