### ISSUE TITLE
What train dataset are used for pwc.pth?

### ISSUE THREAD

**Issue by JunHeum** [feinanshan/M2M_VFI#13]
Hi, @feinanshan.

I appreciate your wonderful work!

I'm wondering if I could know details about the 'pwc.pth' which seems parameters trained on optical flow datasets.

I look forward to receiving your reply.

**Comment by sniklaus** [comment]
Thank you for your interest in our work! It is an off-the-shelf flow estimator (PWC-Net) trained on FlyingChairs, hope that clears things up!

**Comment by feinanshan** [comment]
I am closing this issue. Welcome to reopen it anytime.
