### ISSUE TITLE
Where is the model.pkl file ?

### ISSUE THREAD

**Issue by manojs8473** [feinanshan/M2M_VFI#14]
Hi! I wanted to quickly test the repository on my dataset but I cannot find the pretrained "model.pkl" file. Do I need to train on my own system to generate it ?

**Comment by sniklaus** [comment]
Thank you for your interest in our work!

You can find it here: https://github.com/feinanshan/M2M_VFI/blob/main/Test/README.md

**Comment by manojs8473** [comment]
That helped. Thank you!
