### ISSUE TITLE
JFE output feature channels number

### ISSUE THREAD

**Issue by Eric-chuan** [feinanshan/M2M_VFI#3]
Hi, well done on your new paper. Can I ask you the channels number of each JFE's output respectively. Or where can I find the supplementary material of the paper to learn about more details of your awesome work.

**Comment by feinanshan** [comment]
Hi. The output channels for JEFs are 32, 64, 128, and 256 respectively.  We are hoping the finish the internal check soon and release the codes.

**Comment by Eric-chuan** [comment]
As you mentioned in your paper, each JFE module has a two-layer downsampling CNN. The inputs of them are the original feature and the warped feature, then I get the input channels and output cnannels as follows:  

- JFE_0: 3+2($I_0 concat F_{01}$)--------32
- JFE_1: 32+16-----------64
- JFE_2: 64+32----------128
- JFE_3: 128+64----------256
Are these right？I'm having some trouble reproducing it and would be grateful for any help you can provide

**Comment by feinanshan** [comment]
Hi, the legal check is longer than I expected.   The input/output for JFEs is like the following.

-  3+3+2 -> 32
-   32+32+32 -> 64 
-   64+64+64  -> 128     
- 128+128+128 ->256

**Comment by Eric-chuan** [comment]
Okay, thank you for your warm answer. Do you have an expected date for the code release?

**Comment by feinanshan** [comment]
We are trying to work it out before July, but no guarantee for that.

**Comment by Eric-chuan** [comment]
Get it, thank you so much

**Comment by feinanshan** [comment]
Hi, codes are released.
