### ISSUE TITLE
希望开源下最小预训练推理DEMO

### ISSUE THREAD

**Issue by Baiyuetribe** [feinanshan/M2M_VFI#5]
![image](https://user-images.githubusercontent.com/43716063/173478917-e4739096-367c-4c0a-9891-aeff39b3cc04.png)
如果真实效果如同文献介绍，那么你们已经做到了补帧界的天花板。期待早日普及大众应用。

**Comment by feinanshan** [comment]
Hi 感谢关注。 天花板过誉了，还有很多值得改进的地方。
