### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by Amazingren** [feinanshan/M2M_VFI#8]
Hey @feinanshan,

Hope you everything goes well. Recently, we are doing something related to your this impressive work.

However, during we retrain your model. The error shows like below:
![image](https://user-images.githubusercontent.com/31409716/188238366-06328648-76b5-4ead-a629-0b23aa4782f1.png)

By the way, our environments are  also listed below for your convenience:
```
CUDA: 10.0
python: 3.7
Pytorch: 1.8.0
torchvision: 0.9.0
GPU: NVIDIA TITAN Xp, 12G
```

Thanks again in advance, we are looking forward to hearing from you with some useful suggestions

Bests regards,

**Comment by feinanshan** [comment]
Hi, please delete the last line of `tri_testlist.txt` that just contains a line break.

**Comment by Amazingren** [comment]
> 

Thanks a lot. It works now!

By the way, may I know how long it would cost for training the model from your side on one Titan GPU?
Now I used one TITAN Xp GPU, with batch_size 12. It seems will it will take 4~5 days for the training, is it fine?

Bests,

**Comment by feinanshan** [comment]
Hi, yes it will take about 4 days with a Titan Xp GPU.

**Comment by Amazingren** [comment]
> Hi, yes it will take about 4 days with a Titan Xp GPU.

Got it, thanks a lot!
